name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: Run ESLint
      run: yarn run lint
    - name: Build with Webpack
      run: yarn run build
      env:
        TODO_APP_ROOT: /solid-todo-app-vue/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      if: success() && github.ref == 'refs/heads/main'
      with:
        path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
