name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Enable corepack
      run: corepack enable
    - name: Ensure line endings are consistent
      run: git config --global core.autocrlf input
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install --immutable
    - name: Run ESLint
      run: yarn lint
    - name: Build packages
      run: yarn build
      env:
        TODO_APP_ROOT: /solid-todo-app-vue/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      if: success() && github.ref == 'refs/heads/main'
      with:
        path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
