name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: Run ESLint
      run: yarn run lint
    - name: Build with Vite
      run: yarn run build
